# Generated by Django 6.0.1 on 2026-02-01 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_rename_address1_shippingaddress_shipping_address1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='shipping_postal_code',
            new_name='shipping_zip_code',
        ),
    ]
